export default [
  {
    name: 'Aleksander',
    lastname: 'Szafarz',
    number: 91,
    height: 183,
    position: 'SF',
    age: '2009-06-22',
  },
  {
    name: 'Bartosz',
    lastname: 'Kobiołka',
    number: 28,
    height: 187,
    position: 'PF',
    age: '2007-03-16',
  },
  {
    name: 'Dawid',
    lastname: 'Kocięba',
    number: 0,
    height: 190,
    position: 'PF',
    age: '2001-12-06',
  },
  {
    name: 'Dominik',
    lastname: 'Girgiel',
    number: 34,
    height: 185,
    position: 'SF',
    age: '2007-06-14',
  },
  {
    name: 'Dominik',
    lastname: 'Karaś',
    number: 25,
    height: 179,
    position: 'PG',
    age: '2008-11-26',
  },
  {
    name: 'Dominik',
    lastname: 'Gogolin',
    number: 76,
    height: 185,
    position: 'PF',
    age: '2006-01-07',
  },
  {
    name: 'Filip',
    lastname: 'Kułach',
    number: 22,
    height: 190,
    position: 'SF',
    age: '2001-07-13',
  },
  {
    name: 'Franek',
    lastname: 'Borkowski',
    number: 43,
    height: 190,
    position: 'C',
    age: '2007-08-02',
  },
  {
    name: 'Grzegorz',
    lastname: 'Odrzywałek',
    number: 44,
    height: 185,
    position: 'SG',
    age: '1981-07-25',
  },
  {
    name: 'Igor',
    lastname: 'Szkodny',
    number: 70,
    height: 192,
    position: 'C',
    age: '2003-07-07',
  },
  {
    name: 'Igor',
    lastname: 'Orlef',
    number: 24,
    height: 185,
    position: 'PF',
    age: '2005-02-23',
  },
  {
    name: 'Igor',
    lastname: 'Wnuk',
    number: 77,
    height: 183,
    position: 'SF',
    age: '2007-02-06',
  },
  {
    name: 'Kajetan',
    lastname: 'Kozłowski',
    number: 7,
    height: 185,
    position: 'SG',
    age: '2007-04-14',
  },
  {
    name: 'Karol',
    lastname: 'Karpiński',
    number: 5,
    height: 185,
    position: 'SG',
    age: '2007-11-07',
  },
  {
    name: 'Karol',
    lastname: 'Gramala',
    number: 97,
    height: 179,
    position: 'SG',
    age: '2007-01-01',
  },
  {
    name: 'Kornel',
    lastname: 'Suchocki',
    number: 1,
    height: 187,
    position: 'PG',
    age: '2007-10-09',
  },
  {
    name: 'Krzysztof',
    lastname: 'Żuber',
    number: 18,
    height: 200,
    position: 'C',
    age: '2008-06-23',
  },
  {
    name: 'Kuba',
    lastname: 'Zieliński',
    number: 36,
    height: 183,
    position: 'SF',
    age: '2006-08-26',
  },
  {
    name: 'Maciek',
    lastname: 'Wieczorke',
    number: 55,
    height: 201,
    position: 'C',
    age: '2006-01-01',
  },
  {
    name: 'Maksymilian',
    lastname: 'Elizarov',
    number: 98,
    height: 187,
    position: 'SG',
    age: '2006-01-01',
  },
  {
    name: 'Maksymilian',
    lastname: 'Lipka',
    number: 33,
    height: 179,
    position: 'SG',
    age: '2008-10-04',
  },
  {
    name: 'Mateusz',
    lastname: 'Nizar',
    number: 20,
    height: 185,
    position: 'PF',
    age: '2003-07-23',
  },
  {
    name: 'Mateusz',
    lastname: 'Augustyn',
    number: 17,
    height: 200,
    position: 'C',
    age: '2005-09-18',
  },
  {
    name: 'Mateusz',
    lastname: 'Buń',
    number: 99,
    height: 183,
    position: 'SF',
    age: '2007-01-01',
  },
  {
    name: 'Michał',
    lastname: 'Pilc',
    number: 23,
    height: 179,
    position: 'PG',
    age: '2008-05-23',
  },
  {
    name: 'Patryk',
    lastname: 'Pępek',
    number: 12,
    height: 187,
    position: 'SF',
    age: '2003-01-11',
  },
  {
    name: 'Patryk',
    lastname: 'Kubacki',
    number: 27,
    height: 190,
    position: 'PF',
    age: '2007-02-01',
  },
  {
    name: 'Piotr',
    lastname: 'Oleksy',
    number: 97,
    height: 179,
    position: 'PG',
    age: '2009-01-13',
  },
  {
    name: 'Przemysław',
    lastname: 'Szymański',
    number: 13,
    height: 185,
    position: 'SF',
    age: '2003-12-26',
  },
  {
    name: 'Tomasz',
    lastname: 'Knast',
    number: 45,
    height: 185,
    position: 'SG',
    age: '2004-06-01',
  },
  {
    name: 'Tomasz',
    lastname: 'Gontarewicz',
    number: 4,
    height: 180,
    position: 'SG',
    age: '2002-10-03',
  },
  {
    name: 'Tomasz',
    lastname: 'Dubiel',
    number: 32,
    height: 180,
    position: 'SG',
    age: '2008-05-06',
  },
]
