export default [
  {
    minutes: 14,
    points: 2,
    insideFgm: 1,
    outsideFgm: 0,
    freethrowsFgm: 0,
    insideFga: 2,
    outsideFga: 1,
    freethrowsFga: 0,
    assists: 1,
    reboundsSum: 3,
    reboundsOff: 1,
    reboundsDef: 2,
    blocks: 0,
    steals: 0,
    turnovers: 0,
    fouls: 0,
    eval: 5,
  },
  {
    minutes: 20,
    points: 0,
    insideFgm: 0,
    outsideFgm: 0,
    freethrowsFgm: 0,
    insideFga: 5,
    outsideFga: 0,
    freethrowsFga: 0,
    assists: 0,
    reboundsSum: 3,
    reboundsOff: 0,
    reboundsDef: 3,
    blocks: 0,
    steals: 0,
    turnovers: 1,
    fouls: 3,
    eval: -3,
  },
  {
    minutes: 34,
    points: 0,
    insideFgm: 0,
    outsideFgm: 0,
    freethrowsFgm: 0,
    insideFga: 1,
    outsideFga: 5,
    freethrowsFga: 0,
    assists: 2,
    reboundsSum: 5,
    reboundsOff: 0,
    reboundsDef: 5,
    blocks: 2,
    steals: 0,
    turnovers: 1,
    fouls: 5,
    eval: 4,
  },
  {
    minutes: 17,
    points: 2,
    insideFgm: 1,
    outsideFgm: 0,
    freethrowsFgm: 0,
    insideFga: 3,
    outsideFga: 0,
    freethrowsFga: 0,
    assists: 0,
    reboundsSum: 2,
    reboundsOff: 0,
    reboundsDef: 2,
    blocks: 0,
    steals: 0,
    turnovers: 3,
    fouls: 3,
    eval: -1,
  },
  {
    minutes: 36,
    points: 19,
    insideFgm: 2,
    outsideFgm: 4,
    freethrowsFgm: 3,
    insideFga: 11,
    outsideFga: 9,
    freethrowsFga: 3,
    assists: 1,
    reboundsSum: 4,
    reboundsOff: 1,
    reboundsDef: 3,
    blocks: 1,
    steals: 2,
    turnovers: 6,
    fouls: 3,
    eval: 7,
  },
  {
    minutes: 19,
    points: 5,
    insideFgm: 1,
    outsideFgm: 1,
    freethrowsFgm: 0,
    insideFga: 5,
    outsideFga: 5,
    freethrowsFga: 0,
    assists: 0,
    reboundsSum: 7,
    reboundsOff: 2,
    reboundsDef: 5,
    blocks: 0,
    steals: 2,
    turnovers: 1,
    fouls: 1,
    eval: 5,
  },
  {
    minutes: 38,
    points: 0,
    insideFgm: 0,
    outsideFgm: 0,
    freethrowsFgm: 0,
    insideFga: 3,
    outsideFga: 1,
    freethrowsFga: 0,
    assists: 2,
    reboundsSum: 3,
    reboundsOff: 1,
    reboundsDef: 2,
    blocks: 0,
    steals: 4,
    turnovers: 4,
    fouls: 3,
    eval: 1,
  },
  {
    minutes: 17,
    points: 6,
    insideFgm: 1,
    outsideFgm: 1,
    freethrowsFgm: 1,
    insideFga: 3,
    outsideFga: 1,
    freethrowsFga: 2,
    assists: 0,
    reboundsSum: 3,
    reboundsOff: 1,
    reboundsDef: 2,
    blocks: 0,
    steals: 1,
    turnovers: 2,
    fouls: 2,
    eval: 5,
  },
]
