POST http://localhost:3000/v1/users
Content-Type: application/json

{
  "data": [
    {
      "email": "james@example.com",
      "password": "my-secret-password"
    },
    {
      "email": "monica@example.com",
      "password": "my-secret-password"
    },
    {
      "email": "drake@example.com",
      "password": "my-secret-password"
    }
  ]
}